### ISSUE TITLE
ELK Stack 6.0-rc1 Deployment issue IOError: [Errno 13] Permission denied: '/supervisord.log'

### ISSUE THREAD

**Issue by emre141** [blacktop/docker-elastic-stack#13]
Hi,

I have using below command to create a docker image build.Just added a few path to the filebeat.yaml as below where they are on the my host where Docker file on the same host  

        - /var/log/secure
        - /var/log/messages
        - /var/log/tip.log

And also same way added to the new filter file to the logstash config/logstash/conf.d/12-tip-filter.conf

Then i have run docker build command with my internal registry

docker build . -t 172.30.145.28:5000/elk/elk-stack:6.0-rc1

after push it to the my registry and when i deploy it on openshift i have got below error.

Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]: Traceback (most recent call last):
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/bin/supervisord", line 11, in <module>
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     load_entry_point('supervisor==3.2.4', 'console_scripts', 'supervisord')()
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 367, in main
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     go(options)
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 377, in go
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     d.main()
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 77, in main
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     info_messages)
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1389, in make_logger
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     stdout = self.nodaemon,
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     FileHandler.__init__(self, filename, mode)
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:   File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]:     self.stream = open(filename, mode)
Nov 06 15:20:40 openshiftnode-3.linkplus.int dockerd-current[1388]: IOError: [Errno 13] Permission denied: '/supervisord.log'

**Comment by blacktop** [comment]
There is something special about openshift that makes them behave differently that other docker hosts as can be seen in the official docker image template file here - https://github.com/elastic/elasticsearch-docker/blob/master/templates/Dockerfile.j2#L94

**Comment by emre141** [comment]
This Docker file to create  just only elasticsearch images but the current 6.0 Docker file include each elk stack like elastic,logstash,kibana and etc.So it is so difficult just using seperate elasticsearch docker file and as well logstash etc.How can i use this offical elasticsearch Docker file individual because current 6.0 bundle all of them in a Docker File

**Comment by yoburtu** [comment]
> This Docker file to create just only elasticsearch images but the current 6.0 Docker file include each elk stack like elastic,logstash,kibana and etc.So it is so difficult just using seperate elasticsearch docker file and as well logstash etc.How can i use this offical elasticsearch Docker file individual because current 6.0 bundle all of them in a Docker File

Hi!. Have you solved this issue?. I am installing Elastic Stack 7.0.0 in OpenShift and I have this issue:

Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.4', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 357, in main
    go(options)
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 367, in go
    d.main()
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 71, in main
    self.options.make_logger()
  File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1423, in make_logger
    stdout = self.nodaemon,
  File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/supervisord.log'

Best regards.

**Comment by blacktop** [comment]
closing due to inactivity
