### ISSUE TITLE
IOError: [Errno 13] Permission denied: '/supervisord.log'

### ISSUE THREAD

**Issue by yoburtu** [blacktop/docker-elastic-stack#18]
Hi,

thanks you for support this docker image.

I have installed Elastic Stack 7.0.0 in Openshift, and don't deploy. This is the error log:

Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.4', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 357, in main
    go(options)
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 367, in go
    d.main()
  File "/usr/lib/python2.7/site-packages/supervisor/supervisord.py", line 71, in main
    self.options.make_logger()
  File "/usr/lib/python2.7/site-packages/supervisor/options.py", line 1423, in make_logger
    stdout = self.nodaemon,
  File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/supervisord.log'

Best regards.

**Comment by yoburtu** [comment]
I have solved the issue.

The problem was that in Openshift I didn't have root permissions in my project.

Best regards.
